import streamlit as st
import pandas as pd
import joblib
from pathlib import Path
from src.utils import FEATURE_COLUMNS

# Paths
BASE_DIR = Path(__file__).resolve().parent
MODEL_DIR = BASE_DIR / "models"

# Page config
st.set_page_config(
    page_title="Heart Disease Risk Predictor",
    layout="centered"
)

# Title
st.title("❤️ Heart Disease Risk Prediction")
st.markdown(
    "This application estimates the **risk of heart disease** based on clinical parameters. "
    "It is intended for **educational purposes only**, not medical diagnosis."
)

# Model selection
st.subheader("Model Selection")
model_name = st.selectbox(
    "Choose prediction model",
    ["Logistic Regression (Fast & Interpretable)", "Random Forest (Higher Accuracy)"]
)

# Map readable names to model filenames
MODEL_MAP = {
    "Logistic Regression (Fast & Interpretable)": "logistic_regression",
    "Random Forest (Higher Accuracy)": "random_forest"
}

# Load model safely
model_file = MODEL_MAP[model_name] + ".joblib"
model = joblib.load(MODEL_DIR / model_file)

st.divider()

# Patient info
st.subheader("Patient Information")
col1, col2 = st.columns(2)

with col1:
    age = st.slider("Age (years)", 18, 100, 45)
    sex = st.radio("Sex", ["Male", "Female"])
    trestbps = st.slider("Resting Blood Pressure (mm Hg)", 80, 200, 120)
    chol = st.slider("Serum Cholesterol (mg/dl)", 100, 600, 200)
    thalach = st.slider("Maximum Heart Rate Achieved", 60, 220, 150)

with col2:
    cp = st.selectbox(
        "Chest Pain Type",
        ["Typical Angina", "Atypical Angina", "Non-anginal Pain", "Asymptomatic"]
    )
    fbs = st.radio("Fasting Blood Sugar > 120 mg/dl", ["No", "Yes"])
    restecg = st.selectbox(
        "Resting ECG Result",
        ["Normal", "ST-T Wave Abnormality", "Left Ventricular Hypertrophy"]
    )
    exang = st.radio("Exercise Induced Angina", ["No", "Yes"])
    oldpeak = st.slider("ST Depression Induced by Exercise", 0.0, 6.0, 1.0)

st.divider()

col3, col4 = st.columns(2)

with col3:
    slope = st.selectbox(
        "Slope of Peak Exercise ST Segment",
        ["Upsloping", "Flat", "Downsloping"]
    )

with col4:
    ca = st.selectbox("Number of Major Vessels (0–3)", [0, 1, 2, 3])
    thal = st.selectbox(
        "Thalassemia",
        ["Normal", "Fixed Defect", "Reversible Defect"]
    )

# Convert user input to model format
input_data = {
    "age": age,
    "sex": 1 if sex == "Male" else 0,
    "cp": {"Typical Angina":0, "Atypical Angina":1, "Non-anginal Pain":2, "Asymptomatic":3}[cp],
    "trestbps": trestbps,
    "chol": chol,
    "fbs": 1 if fbs == "Yes" else 0,
    "restecg": {"Normal":0, "ST-T Wave Abnormality":1, "Left Ventricular Hypertrophy":2}[restecg],
    "thalach": thalach,
    "exang": 1 if exang == "Yes" else 0,
    "oldpeak": oldpeak,
    "slope": {"Upsloping":0, "Flat":1, "Downsloping":2}[slope],
    "ca": ca,
    "thal": {"Normal":1, "Fixed Defect":2, "Reversible Defect":3}[thal]
}

# Prediction button
if st.button("🔍 Predict Risk"):
    df_input = pd.DataFrame([input_data])
    prediction = model.predict(df_input)[0]
    probability = model.predict_proba(df_input)[0][1]

    st.divider()

    if prediction == 1:
        st.error(f"⚠️ **High Risk of Heart Disease**\n\nEstimated Risk: **{probability:.1%}**")
    else:
        st.success(f"✅ **Low Risk of Heart Disease**\n\nEstimated Risk: **{probability:.1%}**")

    st.caption("This result is generated by a machine learning model and should not replace professional medical advice.")
